name: Toeggeli-Tournament CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install Dependencies
      run: |
        npm ci --prefix web
        npm ci --prefix functions
    - name: Build Angular
      run: |
        npm run prebuild --prefix web
        npm run build.prod --prefix web
    - name: Archive Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Firebase Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
